spring:
  datasource:
    url: jdbc:h2:./data/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true


logging.level:
  org.hibernate.SQL: debug
  com.querydsl.sql: debug
# org.hibernate.type: trace
