
spring:
  profiles:
    group:
      local:
        - h2
        - app
        - oauth2
        - file
      prod:
        - h2
        - app
        - oauth2
      test:
        - h2
        - app
    active: local
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true


server:
  port: 8081
