spring:
  profiles:
    group:
      local:
        - h2
        - app
        - oauth2
      prod:
        - h2
        - app
        - oauth2
      test:
        - h2
        - app
    active: local
