app:
  auth:
    tokenSecret: 926D9DC90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
  file-root-location: src/main/resources/static/file # 기본 root path 는 프로젝트 디렉토리